version: 1.0.{build}
environment:
  PATH: C:\\Python36-x64;C:\\Python36-x64\\Scripts;$(PATH)
  GMAIL_ADDR:
    secure: z7yQ4wbvIiaICqiDGSpNVQ==
  GMAIL_PWD:
    secure: tp/YNU3a3+EzLjwZtBUAfLPON5H21SoBBvcfrVdSAFY=
install:
  - "python -m pip install --upgrade pip"
  - "pip install pytest"
build_script:
- ps: "pip install ."
test_script:
- ps: "pytest tests"
